# Creating Numpy ndarrays


In [1]:
import numpy as np

In [2]:
# Creating 1D ndarrays

arr1D = np.array([1.1,2.2,3.3,4.4,5.5])
arr1D

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [3]:
# type of the array

type(arr1D)

numpy.ndarray

In [4]:
# Creating 2D ndarrays

arr2D = np.array([[1,2],[3,4]])
arr2D

array([[1, 2],
       [3, 4]])

# Creating any-dimension ndarrays

In [5]:
# creating and ndarray of 2x2x2x2 dimension

arr4D = np.array(range(16)).reshape((2,2,2,2))
arr4D

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

# Creating and ndarray with np.zeros(....)

In [6]:

np.zeros(shape=(2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# Creating and ndarray wiht np.ones(...)

In [7]:
np.ones(shape=(2,2))

array([[1., 1.],
       [1., 1.]])

# Creating and ndarray with np.indentity(.....)

In [8]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Creating and ndarray with np.arrange(...)

In [9]:
np.arange(5)

array([0, 1, 2, 3, 4])

# Creating an ndarray with np.random.randn(...)

In [10]:
np.random.randn(2,2)

array([[-0.18401409, -0.28813853],
       [-1.97922392, -1.5035975 ]])

# Creating a numpy.float64 array

In [11]:
np.array([-1,0,1],dtype = np.float64)

array([-1.,  0.,  1.])

# Creating a numpy.bool array

In [12]:
np.array([-1,0,1],dtype=bool)

array([ True, False,  True])

# ndarrays dtype attribute



In [13]:
arr1D.dtype

dtype('float64')

# Converting underlying data types of ndarray with numpy.ndarrays.astype(...)

In [14]:
# converting arr1D from np.float64 to np.int64, we use the following
arr1D.astype(np.int64).dtype

dtype('int64')

# Direct access to ndarray's element



In [19]:
arr = np.random.randn(3,3)
print(arr)

# indexing the first element with integer index 0, as follows:
print(arr[0])

# accessing the element at the second column of the first row 
print(arr[0][1])

# getting the end of the ndarray
arr[-1]

[[ 0.25920518 -2.12010471  1.63183611]
 [ 0.78927201  0.37115736 -0.43360949]
 [ 1.33344142 -1.57051738 -0.63340895]]
[ 0.25920518 -2.12010471  1.63183611]
-2.1201047118922562


array([ 1.33344142, -1.57051738, -0.63340895])

# ndarray slicing
While single ndarray access is useful, for bulk processing we require access to multiple
elements of the array at once(for example, if the ndarray contains all daily prices of an asset, we might want to process
only all Monday's prices)


# Acessing all ndarray elements after the first one

In [20]:
arr[1:]

array([[ 0.78927201,  0.37115736, -0.43360949],
       [ 1.33344142, -1.57051738, -0.63340895]])

# Fetching all rows, starting from row2 and columns1 and 2

In [22]:
arr[1:,:2]

array([[ 0.78927201,  0.37115736],
       [ 1.33344142, -1.57051738]])

# Slicing with negative indices

This is a less intuitive way of finding the slice of an element at the seccond row and at the second column

In [24]:
arr[1:2,-2:-1]

array([[0.37115736]])

# Slicing with no indices

Slicing with no indices yields the entire row/column. The follwoing code generates a slice containing 
all elements on the third row

In [29]:
print(arr[:][2])

arr[:][:]


[ 1.33344142 -1.57051738 -0.63340895]


array([[ 0.25920518, -2.12010471,  1.63183611],
       [ 0.78927201,  0.37115736, -0.43360949],
       [ 1.33344142, -1.57051738, -0.63340895]])

# Setting values of a slice to 0

Frequently, we will need to set certain values of an ndarray to a given value

In [32]:
arr1 = arr[1:2]
print(arr1)

# let's set every element of arr1 to the value 0, as follows
arr1[:] = 0
print(arr1)

arr

[[0. 0. 0.]]
[[0. 0. 0.]]


array([[ 0.25920518, -2.12010471,  1.63183611],
       [ 0.        ,  0.        ,  0.        ],
       [ 1.33344142, -1.57051738, -0.63340895]])

# Note

ndarray slices are views into the original ndarrays not copies

To create a copy as an ndarray we explicitly call the numpy.ndarray.copy(.....)

In [35]:
arr_copy = arr.copy()

arr_copy[1:2] = 1

print(arr_copy)
arr

[[ 0.25920518 -2.12010471  1.63183611]
 [ 1.          1.          1.        ]
 [ 1.33344142 -1.57051738 -0.63340895]]


array([[ 0.25920518, -2.12010471,  1.63183611],
       [ 0.        ,  0.        ,  0.        ],
       [ 1.33344142, -1.57051738, -0.63340895]])

# Boolean indexing
Numpy provides multiple ways of indexing ndarrays.Numpy arrays can be indexed by using conditions that evaluate
to True or False.Let's start by regenerating an arr ndarray,as follows:

In [40]:
arr = np.random.randn(3,3)
print(arr)

print(np.less(arr,0))

# we can use that arra as index to arr to find the actual negative elements as follows

arr[(arr < 0)]


[[ 0.38373174  0.96308466 -1.49962765]
 [ 1.15641866 -0.54400031 -0.82697472]
 [ 1.52956311 -0.12177522 -0.22578983]]
[[False False  True]
 [False  True  True]
 [False  True  True]]


array([-1.49962765, -0.54400031, -0.82697472, -0.12177522, -0.22578983])