# Creating Numpy ndarrays


In [1]:
import numpy as np

In [2]:
# Creating 1D ndarrays

arr1D = np.array([1.1,2.2,3.3,4.4,5.5])
arr1D

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [3]:
# type of the array

type(arr1D)

numpy.ndarray

In [4]:
# Creating 2D ndarrays

arr2D = np.array([[1,2],[3,4]])
arr2D

array([[1, 2],
       [3, 4]])

# Creating any-dimension ndarrays

In [6]:
# creating and ndarray of 2x2x2x2 dimension

arr4D = np.array(range(16)).reshape((2,2,2,2))
arr4D

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

# Creating and ndarray with np.zeros(....)

In [7]:

np.zeros(shape=(2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# Creating and ndarray wiht np.ones(...)

In [8]:
np.ones(shape=(2,2))

array([[1., 1.],
       [1., 1.]])

# Creating and ndarray with np.indentity(.....)

In [9]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Creating and ndarray with np.arrange(...)

In [10]:
np.arange(5)

array([0, 1, 2, 3, 4])

# Creating an ndarray with np.random.randn(...)

In [11]:
np.random.randn(2,2)

array([[ 0.52092515,  1.24051422],
       [-0.18350416,  2.04094781]])

# Creating a numpy.float64 array

In [12]:
np.array([-1,0,1],dtype = np.float64)

array([-1.,  0.,  1.])

# Creating a numpy.bool array

In [14]:
np.array([-1,0,1],dtype=bool)

array([ True, False,  True])

# ndarrays dtype attribute



In [15]:
arr1D.dtype

dtype('float64')

# Converting underlying data types of ndarray with numpy.ndarrays.astype(...)

In [16]:
# converting arr1D from np.float64 to np.int64, we use the following
arr1D.astype(np.int64).dtype

dtype('int64')

# Direct access to ndarray's element



In [17]:
arr = np.random.randn(3,3)
arr

array([[ 0.2760475 ,  2.13775874,  1.71801691],
       [ 0.6285372 ,  0.14869334,  0.98918028],
       [-0.2320419 ,  0.05023798,  2.27369514]])