# Creating Numpy ndarrays


In [36]:
import numpy as np

In [37]:
# Creating 1D ndarrays

arr1D = np.array([1.1,2.2,3.3,4.4,5.5])
arr1D

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [38]:
# type of the array

type(arr1D)

numpy.ndarray

In [39]:
# Creating 2D ndarrays

arr2D = np.array([[1,2],[3,4]])
arr2D

array([[1, 2],
       [3, 4]])

# Creating any-dimension ndarrays

In [40]:
# creating and ndarray of 2x2x2x2 dimension

arr4D = np.array(range(16)).reshape((2,2,2,2))
arr4D

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

# Creating and ndarray with np.zeros(....)

In [41]:

np.zeros(shape=(2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# Creating and ndarray wiht np.ones(...)

In [42]:
np.ones(shape=(2,2))

array([[1., 1.],
       [1., 1.]])

# Creating and ndarray with np.indentity(.....)

In [43]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Creating and ndarray with np.arrange(...)

In [44]:
np.arange(5)

array([0, 1, 2, 3, 4])

# Creating an ndarray with np.random.randn(...)

In [45]:
np.random.randn(2,2)

array([[-0.28663255, -0.10389852],
       [-2.59226973, -0.4950681 ]])

# Creating a numpy.float64 array

In [46]:
np.array([-1,0,1],dtype = np.float64)

array([-1.,  0.,  1.])

# Creating a numpy.bool array

In [47]:
np.array([-1,0,1],dtype=bool)

array([ True, False,  True])

# ndarrays dtype attribute



In [48]:
arr1D.dtype

dtype('float64')

# Converting underlying data types of ndarray with numpy.ndarrays.astype(...)

In [49]:
# converting arr1D from np.float64 to np.int64, we use the following
arr1D.astype(np.int64).dtype

dtype('int64')

# Direct access to ndarray's element



In [50]:
arr = np.random.randn(3,3)
print(arr)

# indexing the first element with integer index 0, as follows:
print(arr[0])

# accessing the element at the second column of the first row 
print(arr[0][1])

# getting the end of the ndarray
arr[-1]

[[ 0.77787163 -1.77197428 -1.34001923]
 [-0.44087757  0.75400284 -1.1536232 ]
 [ 0.27296266 -0.67201968  0.48011441]]
[ 0.77787163 -1.77197428 -1.34001923]
-1.7719742846808837


array([ 0.27296266, -0.67201968,  0.48011441])

# ndarray slicing
While single ndarray access is useful, for bulk processing we require access to multiple
elements of the array at once(for example, if the ndarray contains all daily prices of an asset, we might want to process
only all Monday's prices)


# Acessing all ndarray elements after the first one

In [51]:
arr[1:]

array([[-0.44087757,  0.75400284, -1.1536232 ],
       [ 0.27296266, -0.67201968,  0.48011441]])

# Fetching all rows, starting from row2 and columns1 and 2

In [52]:
arr[1:,:2]

array([[-0.44087757,  0.75400284],
       [ 0.27296266, -0.67201968]])

# Slicing with negative indices

This is a less intuitive way of finding the slice of an element at the seccond row and at the second column

In [53]:
arr[1:2,-2:-1]

array([[0.75400284]])

# Slicing with no indices

Slicing with no indices yields the entire row/column. The follwoing code generates a slice containing 
all elements on the third row

In [54]:
print(arr[:][2])

arr[:][:]


[ 0.27296266 -0.67201968  0.48011441]


array([[ 0.77787163, -1.77197428, -1.34001923],
       [-0.44087757,  0.75400284, -1.1536232 ],
       [ 0.27296266, -0.67201968,  0.48011441]])

# Setting values of a slice to 0

Frequently, we will need to set certain values of an ndarray to a given value

In [55]:
arr1 = arr[1:2]
print(arr1)

# let's set every element of arr1 to the value 0, as follows
arr1[:] = 0
print(arr1)

arr

[[-0.44087757  0.75400284 -1.1536232 ]]
[[0. 0. 0.]]


array([[ 0.77787163, -1.77197428, -1.34001923],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.27296266, -0.67201968,  0.48011441]])

# Note

ndarray slices are views into the original ndarrays not copies

To create a copy as an ndarray we explicitly call the numpy.ndarray.copy(.....)

In [56]:
arr_copy = arr.copy()

arr_copy[1:2] = 1

print(arr_copy)
arr

[[ 0.77787163 -1.77197428 -1.34001923]
 [ 1.          1.          1.        ]
 [ 0.27296266 -0.67201968  0.48011441]]


array([[ 0.77787163, -1.77197428, -1.34001923],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.27296266, -0.67201968,  0.48011441]])

# Boolean indexing
Numpy provides multiple ways of indexing ndarrays.Numpy arrays can be indexed by using conditions that evaluate
to True or False.Let's start by regenerating an arr ndarray,as follows:

In [57]:
arr = np.random.randn(3,3)
print(arr)

print(np.less(arr,0))

# we can use that arra as index to arr to find the actual negative elements as follows

print(arr[(arr < 0)]) 


# we can combine multip;e conditions with & (and) ns | (or) operators.
# Pythons & and | Boolean operators do not work on ndarrays since they are for scalars



print((arr > -1) & (arr < 1))

arr[((arr > -1) & (arr < 1))]


[[ 0.05083773 -1.12732373  0.6395469 ]
 [ 0.72571487 -0.16193655  2.14630936]
 [-0.59737481 -1.93530074  0.23869635]]
[[False  True False]
 [False  True False]
 [ True  True False]]
[-1.12732373 -0.16193655 -0.59737481 -1.93530074]
[[ True False  True]
 [ True  True False]
 [ True False  True]]


array([ 0.05083773,  0.6395469 ,  0.72571487, -0.16193655, -0.59737481,
        0.23869635])

# Indexing with arrays

ndarray indexing also allows us to directly pass lists of indices of interst.Let's first 
generate an ndarray of randome values to use, as follows:



In [58]:
print(arr)

# select the first the first and third rows, using the following code
print("")
print(arr[[0,2]])

# we can combine row and column indexing using arrays, as follows:
print("")
print(arr[[0,2],[1]])

# the folowing code picks up the third row followed by the second row
arr[[2,0]] 


[[ 0.05083773 -1.12732373  0.6395469 ]
 [ 0.72571487 -0.16193655  2.14630936]
 [-0.59737481 -1.93530074  0.23869635]]

[[ 0.05083773 -1.12732373  0.6395469 ]
 [-0.59737481 -1.93530074  0.23869635]]

[-1.12732373 -1.93530074]


array([[-0.59737481, -1.93530074,  0.23869635],
       [ 0.05083773, -1.12732373,  0.6395469 ]])

# Basic ndarray operations


In [59]:
arr2D

array([[1, 2],
       [3, 4]])

In [60]:
# Scalar multiplication with an ndarray
arr2D * 4

array([[ 4,  8],
       [12, 16]])

# Linear combinations of ndarrays

The following is a combinations of scalar and ndarrays operations,as well as operation between ndarrays



In [61]:
2 * arr2D + 3*arr2D

array([[ 5, 10],
       [15, 20]])

# Exponentiation of ndarrays

In [62]:
arr2D ** 2

array([[ 1,  4],
       [ 9, 16]])

# Addition of an ndarray with a scalar

In [63]:
arr2D + 10

array([[11, 12],
       [13, 14]])

# Transposing a matrix

In [64]:
arr2D.transpose()

array([[1, 3],
       [2, 4]])

# Changing the layout of an ndarray

The np.ndarray.reshape(...) method allows us to change the layout(shape) of 
the ndarray without changing its data to compatible shape



In [65]:
# For instance, to reshape arr2D from 2x2 to 4x1 , we use the following code
print(arr2D.reshape((4,1)))

# The following code example combines np.random.randn(....) and np.ndarray.reshape(....)
# to create 3x3 ndarray of random values

arr = np.random.randn(9).reshape((3,3))
arr

[[1]
 [2]
 [3]
 [4]]


array([[-0.20822801,  0.00236542,  0.08191605],
       [ 0.52232833,  2.30153534,  0.69477351],
       [-0.60125415,  1.63130956,  0.70061611]])

In [66]:
# Finding the minimum value in an ndarray
np.min(arr)

-0.6012541543818718

In [67]:
# Calculating the absolute value

np.abs(arr)

array([[0.20822801, 0.00236542, 0.08191605],
       [0.52232833, 2.30153534, 0.69477351],
       [0.60125415, 1.63130956, 0.70061611]])

In [68]:
# Calculating the mean of an ndarray
print(np.mean(arr))

# Finding the mean along the columns by specifying the axis = parameter, as follows
print(np.mean(arr,axis=0))

# Finding the mean along the rows by running the following code
np.mean(arr,axis=1)

0.5694846824610219
[-0.09571795  1.31173677  0.49243522]


array([-0.04131551,  1.17287906,  0.5768905 ])

# Finding the index of the maximum value in an ndarray
Often, we're interested in finding where in an array its largest value is. The np.armax(...) does it


In [75]:
print(np.argmax(arr))


# The np.argmax(....) method also accepts the axis =parameter to perform operation on row-wise

np.argmax(arr,axis=1)



4


array([2, 1, 1], dtype=int64)

# Calculating the cumulative sum of elements of an ndarray

Notice the differnce between a cumulative sum and a sum . A cumulative sum is an array 
of a  running total,whereas a sum is a single number



In [79]:
print(arr)

# cumulative sum
print(np.cumsum(arr))


# cumulative sum along the row
np.cumsum(arr,axis=1)

[[-0.20822801  0.00236542  0.08191605]
 [ 0.52232833  2.30153534  0.69477351]
 [-0.60125415  1.63130956  0.70061611]]
[-0.20822801 -0.20586259 -0.12394654  0.39838178  2.69991712  3.39469063
  2.79343647  4.42474603  5.12536214]


array([[-0.20822801, -0.20586259, -0.12394654],
       [ 0.52232833,  2.82386366,  3.51863717],
       [-0.60125415,  1.03005541,  1.73067151]])

# Finding NaNs in an ndarray
Missing or unknown values are often represented in Numpy using a Not a number
(NaN) value. For many numerical methods, these must be removed or replaced with 
an interpolation



In [80]:
# setting the second row to Nan
arr[1,:] = np.nan;
arr

array([[-0.20822801,  0.00236542,  0.08191605],
       [        nan,         nan,         nan],
       [-0.60125415,  1.63130956,  0.70061611]])

In [81]:
# finding if Nan values exist
np.isnan(arr)

array([[False, False, False],
       [ True,  True,  True],
       [False, False, False]])

# Finding the truth values of x1 > x2 of two ndarrays

Boolean ndarrays are an efficient way of obtaining indices for values of interest.

In [82]:
arr1 = np.random.randn(9).reshape((3,3))

arr1

array([[-0.50418891, -2.39554485, -1.49808908],
       [-0.39923548, -0.01856961,  0.50321137],
       [ 1.58168984,  0.93755709, -0.6604453 ]])

In [83]:
# Similarly,let's build another arr2 ndarray, as follows:
arr2 = np.random.randn(9).reshape((3,3))
arr2

array([[ 9.39501718e-02,  1.94408822e-01, -5.93823846e-04],
       [-2.06527607e-02,  8.09464196e-01, -1.07895617e+00],
       [-1.15948797e+00,  1.38696206e-01, -1.25295085e+00]])

In [84]:
# The np.greater(....) function is a binary ufunc that generates a True value
# when the left-hand-side value in the ndarray is greater  than right hand side in the ndarray

np.greater(arr1,arr2)

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [85]:
# output is the same as above

arr1 > arr2

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

# any and all Boolean operations on ndarrays

In addition to relational operators, Numpy supports additional methods for testing
conditions on matrices values

In [86]:
arr_bool = (arr > -0.5) & (arr < 0.5)

arr_bool

array([[ True,  True,  True],
       [False, False, False],
       [False, False, False]])

In [87]:
# The following numpy.ndarray.any() method returns True if any element is True otherwise returns False

arr_bool.any()

True

In [88]:
# Again, it accepts the common axis= parameter and behaves as expected
arr_bool.any(axis=1)

array([ True, False, False])

In [89]:
# The following numpy.ndarray.all() method returns True when all elements are True, and False otherwise
arr_bool.all()

False

In [90]:
# It also accepts the axis= parameter, as follows:
arr_bool.all(axis=1)

array([ True, False, False])

# Sorting ndarrays

Finding an element in a sorted ndarray is faster than processing all elements of the ndarray

In [91]:
arr1D = np.random.randn(10)
arr1D

array([ 0.91420705,  0.68876904, -2.06661513,  0.47546496, -1.26748921,
       -0.56507078, -0.0114976 , -1.00571721, -2.36131698,  0.01416545])

In [92]:
# The np.sort(.....) method is pretty straightforward, as can be seen here:
np.sort(arr1D)

array([-2.36131698, -2.06661513, -1.26748921, -1.00571721, -0.56507078,
       -0.0114976 ,  0.01416545,  0.47546496,  0.68876904,  0.91420705])